### ISSUE TITLE
Tests for Likelihood Gradient Calculation

### ISSUE THREAD

**Issue by wbailey** [sbyrnes/logistical.js#13]
In order to find the coefficients that optimize the likelihood we do the following:

![image](https://cloud.githubusercontent.com/assets/176914/6511323/e3f62f18-c320-11e4-9209-ef60b0ad94ca.png)

This ultimately gives us the following formula we can use to maximize the gradient in k-space and determine the coefficient:

![image](https://cloud.githubusercontent.com/assets/176914/6511987/82e49bf6-c325-11e4-991e-e1cb3ca6ac5e.png)

We therefore need tests that will support the code that ultimately solves this equation

**Comment by sbyrnes** [comment]
Just to be clear, we want a test that verifies that the gradient of the likelihood is computed correctly? Or we want to test that the descent converges?

**Comment by wbailey** [comment]
Previously considered only the correct calculation use case.  I am interested if you have an idea on how to test for algorithm convergence as well.

**Comment by sbyrnes** [comment]
In that case, I changed the name of the ticket as it will only test the Likelihood Gradient calculation. 

Testing convergence should be a matter of running a series of N descent steps and seeing if the values are converging or diverging. However, I think this would be overkill since you can tell if the descent is working if the classifier itself works. No need to test both, assuming we test that all the component calculations are correct.
